version: '3.8'
services:
  neo4j:
    container_name: neo4j
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-conf:/conf
    environment:
      - NEO4J_AUTH=neo4j/neo4jpasswprd
volumes:
  neo4j-data:
  neo4j-logs:
  neo4j-conf: